window.projects = {
    'p1': {
        name: 'Leatherwalk',
        year: '2023',
        link: '#',
        description: "Introducing LeatherWalk, a footwear brand dedicated to timeless craftsmanship and personalized leather shoes. With the slogan 'Walk Forever' LeatherWalk blends quality and legacy to offer both casual and official footwear that speaks to individual style and durability. <br>I took on the challenge of building the digital face of LeatherWalk — a custom footwear platform designed to evolve into a full-fledged e-commerce experience. Using HTML, CSS, and JavaScript, I crafted the frontend with careful attention to detail, ensuring each interaction feels as premium as the products themselves. I designed the layout in Figma, paying close attention to intuitive navigation, color harmony, and visual storytelling that aligns with the brand’s identity. While the project is still in development, the goal is to create a seamless shopping experience for shoe enthusiasts — from exploring handcrafted designs to placing custom orders. LeatherWalk is not just about shoes, it’s about building a digital space that reflects the soul of the brand: legacy, comfort, and style.",
        image1: 'https://res.cloudinary.com/dab2002/image/upload/v1748628899/leatherwalk1-min_y45qnz.png',
        image2: 'https://res.cloudinary.com/dab2002/image/upload/v1748972868/Leatherwalk2_mhpqdk.png',
        image3: 'https://res.cloudinary.com/dab2002/image/upload/v1749024463/Leatherwalk3_mvmklu.png',
        image4: 'https://res.cloudinary.com/dab2002/image/upload/v1748965989/Leatherwalk4_b3xixx.png',
    },
    'p2': {
        name: 'HALD Visuals',
        year: '2024',
        link: 'https://www.haldvisuals.com',
        description: "Introducing HALD Visuals, a vibrant film production company based in Nairobi, Kenya, known for crafting impressionable visuals and unforgettable experiences through film and photography. Collaborating with innovative brands and visionary individuals, HALD brings stories to life with creative depth and cinematic precision. <br>For this project, I had the opportunity to assist a fellow developer in bringing the HALD Visuals website to life. While I wasn’t the lead, I contributed to refining frontend elements and supporting the implementation of interactive components using JavaScript. The site reflects the energy and artistic vision of the brand — bold, clean, and immersive. Working on HALD Visuals gave me a chance to engage with a creative-driven brand and apply my skills in a collaborative setting, helping shape a digital experience that matches the high production value HALD is known for.",
        image1: 'https://res.cloudinary.com/dab2002/image/upload/v1748628606/HALD1_fbu3i2.png',
        image2: 'https://res.cloudinary.com/dab2002/image/upload/v1748850573/HALD2_rtxffj.png',
        image3: 'https://res.cloudinary.com/dab2002/image/upload/v1748854699/HALD3_lt88te.png',
        image4: 'https://res.cloudinary.com/dab2002/image/upload/v1748850638/HALD4_eddq0u.png',
    },
    'p3': {
        name: 'Haniffa Crochets',
        year: '2025',
        link: '#',
        description: "Haniffa Crochets is a charming one-page website designed to showcase the creative craftsmanship of Haniffa, a passionate crochet artist. The site highlights her unique handmade pieces through a clean and inviting gallery, paired with a short introduction and accessible contact section to connect with potential clients and admirers of her work. <br>I designed and developed the site with simplicity and elegance in mind, ensuring the layout felt personal and easy to navigate. The visual theme features varying shades of green, thoughtfully chosen to complement the client’s logo and overall brand aesthetic. This project focused more on storytelling through design — using layout, color, and structure to let the work speak for itself. It’s a small but meaningful site that reflects the heart and personality behind the brand.",
        image1: 'https://res.cloudinary.com/dab2002/image/upload/v1748628621/haniffa1_hs7hd6.png',
        image2: 'https://res.cloudinary.com/dab2002/image/upload/v1749027238/still-life-crochet-plushies_11zon_wybfwf.jpg',
        image3: 'https://res.cloudinary.com/dab2002/image/upload/v1750608022/Haniffa3_xgkmap.png',
        image4: 'https://res.cloudinary.com/dab2002/image/upload/v1750530170/Haniffa4_yf7upn.png',
    },
    'p4': {
        name: 'Young Stripes',
        year: '2025',
        link: '#',
        description: "Young Stripes is an impactful initiative focused on empowering young people through STEM and leadership development. The organization works to raise the personal, academic, and professional profiles of students by connecting them with schools, universities, and industry partners through practical, sustained learning experiences. <br>I developed a one-page informational website for Young Stripes, aimed at introducing the mission, values, and ongoing work of the organization. The site is still in progress, with plans to expand as the initiative grows, but the current structure provides a clean and accessible overview for visitors. My goal with the design was to keep it clear and purposeful, ensuring that the message of youth empowerment and long-term engagement comes through strongly across all sections.",
        image1: 'https://res.cloudinary.com/dab2002/image/upload/v1750527525/Youngstripes1_qbmmpa.png',
        image2: 'https://res.cloudinary.com/dab2002/image/upload/v1750611303/Youngstripes2_yze3jr.png',
        image3: 'https://res.cloudinary.com/dab2002/image/upload/v1750613754/Youngstripes3_zppqb0.png',
        image4: 'https://res.cloudinary.com/dab2002/image/upload/v1750747211/Youngstripes4_x1niky.png',
    },
    'p5': {
        name: 'Tasty Food',
        year: '2025',
        link: '#',
        description: "Introducing the Interactive Restaurant Web App — a modern solution tailored for restaurants seeking a smoother, more efficient dining experience. Designed to replace static PDF menus and outdated POS systems, this web-based platform brings real-time order management and dynamic menu interaction to the forefront of restaurant service. <br>I took on the challenge of designing and developing this digital menu system from scratch, focusing on both the customer-facing interface and the admin dashboard. From viewing detailed food items to customizing and placing orders, every feature was crafted to enhance usability while remaining lightweight and responsive. The project demanded a balance between functionality and clean design, and I dedicated myself to building a solution that could adapt to the real-world demands of restaurants in Nairobi. What began as a school project quickly became a passion project, and I poured hours into testing and refining both the user and admin experiences. Throughout the process, I focused on performance, accessibility, and real-time functionality — building a product that could scale and evolve with restaurant needs.",
        image1: 'https://res.cloudinary.com/dab2002/image/upload/v1748858947/Tastyfood1_tll6xn.png',
        image2: 'https://res.cloudinary.com/dab2002/image/upload/v1748860898/Tastyfood2_wux8oa.png',
        image3: 'https://res.cloudinary.com/dab2002/image/upload/v1748864658/Tastyfood3_jjckfi.png',
        image4: 'https://res.cloudinary.com/dab2002/image/upload/v1748865456/Tastyfood4_lnjle1.png',
    },
    // Add more products as needed
};